apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs-express-mysql=docker.io/256606/nodejs-express-mysql
    argocd-image-updater.argoproj.io/nodejs-express-mysql.update-strategy: newest-build
spec:
  project: default

  source:
    repoURL: https://github.com/memrekaraaslan/nodejs-express-mysql.git
    targetRevision: master
    path: helm/nodejs-express-mysql
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true