apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 256606/nodejs-express-mysql:1.0.x
    argocd-image-updater.argoproj.io/nodejs-express-mysql.update-strategy: semver
    argocd-image-updater.argoproj.io/nodejs-express-mysql.helm-value: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "#all-cloudopscenter"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "#all-cloudopscenter"
spec:
  project: default

  source:
    repoURL: https://github.com/memrekaraaslan/nodejs-express-mysql.git
    targetRevision: master
    path: helm/nodejs-express-mysql
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true