configs:
  secret:
    create: false

  registries:
    enabled: true
    registries:
      - name: Docker Hub
        api_url: https://index.docker.io/v1/
        prefix: docker.io
        credentials: secret:dockerhub-secret
        default: true

  git:
    writeGitCredentials: true
    commitUser:
      name: ArgoCD Image Updater
      email: updater@argocd.io
    credentials:
      - url: https://github.com/memrekaraaslan/nodejs-express-mysql.git
        usernameSecret:
          name: git-creds
          key: username
        passwordSecret:
          name: git-creds
          key: password

image:
  tag: v0.12.0

logLevel: info