namespace: production

# Note: replicaCount is ignored when hpa.enabled is true
replicaCount: 2

image:
  repository: 256606/nodejs-express-mysql
  tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
