namespace: production
replicaCount: 2

image:
  repository: 256606/nodejs-express-mysql
  tag: 1.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

