namespace: dev
replicaCount: 1

image:
  repository: 256606/nodejs-express-mysql
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi


