name: Build & Push Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - app/**
      - server.js
      - Dockerfile
      - package.json

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag using GitHub run number
        run: echo "IMAGE_TAG=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        run: |
          docker build -t 256606/nodejs-express-mysql:${{ env.IMAGE_TAG }} .
          docker push 256606/nodejs-express-mysql:${{ env.IMAGE_TAG }}