name: Terraform CI/CD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'terraform/**'
    branches: [ master ]
  push:
    paths:
      - 'terraform/**'
    branches: [ master ]

jobs:
  terraform:
    name: Terraform Format, Plan, Apply and Show
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/k8s-setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform fmt -check

      - name: Terraform Init
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          terraform plan \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="vpc_name=${{ secrets.VPC_NAME }}" \
            -var="cluster_name=${{ secrets.CLUSTER_NAME }}" \
            -var="environment=${{ secrets.ENVIRONMENT }}" \
            -var="github_username=${{ secrets.GH_USERNAME }}" \
            -var="github_pat=${{ secrets.GH_PAT }}" \
            -var="github_repo_url=${{ secrets.GH_REPO_URL }}" \
            -var="dockerhub_dockerconfigjson=${{ secrets.DOCKERHUB_DOCKERCONFIGJSON }}" \
            -var="slack_bot_token=${{ secrets.SLACK_BOT_TOKEN }}"
        env:
          TF_LOG: DEBUG
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="vpc_name=${{ secrets.VPC_NAME }}" \
            -var="cluster_name=${{ secrets.CLUSTER_NAME }}" \
            -var="environment=${{ secrets.ENVIRONMENT }}" \
            -var="github_username=${{ secrets.GH_USERNAME }}" \
            -var="github_pat=${{ secrets.GH_PAT }}" \
            -var="github_repo_url=${{ secrets.GH_REPO_URL }}" \
            -var="dockerhub_dockerconfigjson=${{ secrets.DOCKERHUB_DOCKERCONFIGJSON }}" \
            -var="slack_bot_token=${{ secrets.SLACK_BOT_TOKEN }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Show
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform show -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}